# Generated by Django 4.0.6 on 2022-07-10 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('workplace', models.CharField(choices=[('onsite', 'Onsite'), ('wfh', 'Wfh'), ('hybrid', 'Hybrid')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full_time'), ('part_time', 'Part_time'), ('contract', 'Contract')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('field_of_specialization', models.CharField(choices=[('engineer', 'Engineer'), ('hr', 'Hr')], max_length=30)),
                ('organization', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['first_name'],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('school', 'School'), ('company', 'Company')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('field_of_specialization', models.CharField(choices=[('engineer', 'Engineer'), ('hr', 'Hr')], max_length=30)),
                ('organization', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['first_name'],
            },
            bases=('accounts.user',),
        ),
    ]
